name: Despliegue a GitHub Pages

on:
  push:
    branches:
      - main # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configurar Clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Desplegar a GitHub Pages
        run: |
          git config --global user.email "tu_correo@ejemplo.com"
          git config --global user.name "Tu Nombre"
          git push origin main:gh-pages

